image: ubuntu:20.04

stages:
  - setup-env
  - deploy

setup-env:
  stage: setup-env
  script:
  - apt-get -qq update && apt-get -qq install -y python3.8 python3-pip
  - apt-get -qq update
  - pip install pytorch-lightning
#deploy:
#  deploy:
#  - grid login --username $USERNAME --api-key $KEY
#  - grid run hello.py
