image: ubuntu:20.04

stages:
  - setup-env
  - deploy

setup-env:
  stage: setup-env
  script:
  - apt-get -qq update && apt-get -qq install -y python3.8 python3-pip
  - apt-get -qq update
  - pip install pytorch-lightning
deploy:
  stage: deploy
  script:
  - grid login --username ${{ secrets.GRID_USERNAME }} --api-key ${{ secrets.GRID_KEY }}
  - grid run gridai.py
