image: alpine

stages:
  - setup-env
  - deploy

setup-env:
  setup-env:
  - apt-get -qq update && apt-get -qq install -y python
  - apt-get -qq update
  - apt-get -qq install -y python python-virtualenv python-pip
  - virtualenv venv
  - . venv/bin/activate
  - python -V
  - pip install pytorch-lightning
