image: ubuntu:20.04

stages:
  - run_lightning_example
  
run_lightning_example:
  stage: grid_run_example
  script:
  - apt-get -qq update && apt-get -qq install -y python3.8 python3-pip git
  - apt-get -qq update
  - pip install --upgrade  lightning_grid==0.8.15
  - grid login --username="$GRID_USER" --key="$GRID_APIKEY"
  - git clone https://github.com/williamFalcon/hello
  - cd hello
  - grid run --instance_type=g4dn.xlarge hello.py --number 1 --food_item "['pizza', 'hotdog']" 

