image: ubuntu:20.04

stages:
  - deploy
  
deploy:
  stage: deploy
  script:
  - apt-get -qq update && apt-get -qq install -y python3.8 python3-pip git
  - apt-get -qq update
  - pip install lightning-grid --upgrade
  - echo $GRID_APIKEY
  
