name: 'Grid.ai Login'
inputs:
  grid_url:  
    required: false
    default: 
    type: string
  python_version:  
    required: false
    default: 3.8
    type: string
  griai_cli_version:  
    required: false
    default: 
    type: string
  gridai_username:
    required: true
    default:
    type: string
  gridai_key:
    required: true
    default:
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }} # min version supported by Grid.ai    
    - run: python -m pip install --upgrade pip
      shell: bash
    - run: |
        if [ -z "${{ inputs.griai_cli_version }}" ]; then
          pip install lightning-grid --upgrade
        else
          pip install lightning-grid==${{ inputs.griai_cli_version }} --upgrade
        fi
      shell: bash
    - run: |
        if [ ! -z "${{ inputs.grid_url }}" ]; then 
          export GRID_URL=${{ inputs.grid_url }}
          echo "GRID_URL=${{ inputs.grid_url }}" >> $GITHUB_ENV 
        fi
      shell: bash
    - run: grid login --username ${{ inputs.gridai_username }} --key ${{ inputs.gridai_key }}
      shell: bash
