name: 'Grid.ai Login'
inputs:
  grid_url:  
    required: false
    default: 
    type: string
  python_version:  
    required: false
    default: 3.8
    type: string
  username:
    required: true
    default:
    type: string
  key:
    required: true
    default:
    type: string
runs:
  using: "composite"
  steps:
    - run: python -m pip install --upgrade pip
      shell: bash
    - run: pip install lightning-grid --upgrade
      shell: bash
    - run: |
        if [ ! -z "${{ inputs.grid_url }}" ]; then 
          export GRID_URL=${{ inputs.grid_url }}
          echo "GRID_URL=${{ inputs.grid_url }}" >> $GITHUB_ENV 
        fi
      shell: bash
    - run: grid login --username ${{ inputs.username }} --key ${{ inputs.key }}
      shell: bash
