name: 'Grid.ai Login'
inputs:
  grid-url:  
    required: false
    default: 
    type: string
  python-version:  
    required: false
    default: 3.8   # min version supported by Grid.ai 
    type: string
  gridai-python-modules:  
    required: false
    default: "lightning-grid requests_toolbelt"
    type: string
    description: "space separate list of python packages to install"
  add-module-version:  
    required: true
    default: "true"
    type: string
  gridai-username:
    required: true
    default:
    type: string
  gridai-key:
    required: true
    default:
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}   

    - run: |
        echo ${{ inputs.gridai-python-modules }} | tr ' ' '\n' | while read m; do
          export PACKAGE_JSON_URL="https://pypi.org/pypi/${m}/json"
          if [ -z "${{ inputs.add-module-version }}" ]; then
            echo ${m} >> gridai-cli-requirements.txt
          else
            LATEST_VERSION=$(curl -L -s "$PACKAGE_JSON_URL" | jq  -r '.releases | keys | .[]' | sort -V | tail -1)
            echo ${m}==$LATEST_VERSION
            echo ${m}==${LATEST_VERSION} >> gridai-cli-requirements.txt
          fi  
        done
      shell: bash

    - run: |
        pip install -r gridai-cli-requirements.txt
      shell: bash
      
    - run: |
        if [ ! -z "${{ inputs.grid-url }}" ]; then 
          export grid-url=${{ inputs.grid-url }}
          echo "grid-url=${{ inputs.grid-url }}" >> $GITHUB_ENV 
        fi
      shell: bash

    - run: grid login --username ${{ inputs.gridai-username }} --key ${{ inputs.gridai-key }}
      shell: bash
