name: 'Grid.ai Login'
inputs:
  grid_url:  
    required: false
    default: 
    type: string
  python_version:  
    required: false
    default: 3.8
    type: string
  username:
    required: true
    default:
    type: string
  gridai_key:
    required: true
    default:
    type: string
runs:
  using: "composite"
    - run: python -m pip install --upgrade pip
    - run: pip install lightning-grid --upgrade
    - run: if [ ! -z "${{ inputs.grid_url }} "]; then export GRID_URL=${{ inputs.grid_url }}; fi
    - run: grid login --username ${{ inputs.username }} --key ${{ inputs.gridai_key }}
    - run: echo "GRID_URL=${{ inputs.grid_url }}" >> $GITHUB_ENV 