name: 'Grid.ai Login'
inputs:
  grid_url:  
    required: false
    default: 
    type: string
  python_version:  
    required: false
    default: 3.8
    type: string
  username:
    required: true
    default:
    type: string
  key:
    required: true
    default:
    type: string
runs:
  using: "composite"
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}
    - run: |
        python -m pip install --upgrade pip
    - run: |
        pip install lightning-grid --upgrade
    - run: |
        if [ ! -z "${{ inputs.grid_url }} "]; then export GRID_URL=${{ inputs.grid_url }}; fi
        grid login --username ${{ inputs.username }} --key ${{ inputs.key }}
        echo "GRID_URL=${{ inputs.grid_url }}" >> $GITHUB_ENV 