name: 'Grid.ai Login'
inputs:
  # required
  gridai-username:
    required: true
    default:
    type: string
    description: "Grid.ai username used in grid login command"
  gridai-key:
    required: true
    default: 
    type: string
    description: "Grid.ai key used in grid login command"
  # optional
  ssh-key-type:
    required: false
    default: ed25519
    type: string
    description: "ssh key type to generate. default=ed25519.  [dsa | ecdsa | ed25519 | rsa]"  
  grid-url:  
    required: false
    default: 
    type: string
    description: "URL to reach Grid.ai services"
  python-venv:  
    required: false
    default: ""    
    type: string
    description: "'', venv, conda are options"
  python-version:  
    required: false
    default: 3.8    
    type: string
    description: "3.8 is the minimum Python version required for Grid.ai"
  gridai-python-modules:  
    required: false
    default: "lightning-grid"
    type: string
    description: "Space separate list of Python modules to install"
  add-module-version:  
    required: false
    default: "true"
    type: string
    description: "Suffix the latest Python module version. eg: lightning-grid to lightning-grid=0.4.1 (for example)"
outputs:
  user-team:
    value: ${{ steps.gridai-obj-status.outputs.user-team }}
    description: "team name of the user"
  user-role:
    value: ${{ steps.gridai-obj-status.outputs.user-role }}
    description: "role of the user"
runs:
  using: "composite"
  steps:
    - run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}   

    - run: |
        echo ${{ inputs.gridai-python-modules }} | tr ' ' '\n' | while read m; do
          export PACKAGE_JSON_URL="https://pypi.org/pypi/${m}/json"
          if [ -z "${{ inputs.add-module-version }}" ]; then
            echo ${m} >> gridai-cli-requirements.txt
          else
            LATEST_VERSION=$(curl -L -s "$PACKAGE_JSON_URL" | jq  -r '.releases | keys | .[]' | sort -V | tail -1)
            echo ${m}==$LATEST_VERSION
            echo ${m}==${LATEST_VERSION} >> gridai-cli-requirements.txt
          fi  
        done
      shell: bash

    - run: |
        case "${{ inputs.python-venv }}" in 
          venv)
            pip install virtualenv
            virtualenv gridai_venv
            if [ -f gridai_venv/bin/activate ]; then 
              source gridai_venv/bin/activate
            else
              ls -R gridai_venv
              source gridai_venv\\Scripts\\activate
            fi
            ;;
          *)
            ;;
        esac
      shell: bash

    - run: |
        pip install -r gridai-cli-requirements.txt
        pip install -r requirements.txt
      shell: bash
      
    - run: |
        if [ ! -z "${{ inputs.grid-url }}" ]; then 
          export grid-url=${{ inputs.grid-url }}
          echo "grid-url=${{ inputs.grid-url }}" >> $GITHUB_ENV 
        fi
      shell: bash

    - run: |
        ssh-keygen -t ${{ inputs.ssh-key-type }}  -C "${{ inputs.gridai-username }}" -N "" -f ~/.ssh/id_${{ inputs.ssh-key-type }}
      shell: bash

    - run: |
        gridai.py cli "grid login --username ${{ inputs.gridai-username }} --key ${{ inputs.gridai-key }}"
      shell: bash

    - id: gridai-obj-status
      run: |
        gridai.py cli "grid user" | tee grid.user.log
        if [ ! -z "$(cat grid.user.log | grep '^Teams:$')" ]; then 
          tail -1 grid.user.log | awk '{print "::set-output name=user-team::"$1;print "::set-output name=user-role::"$4;}'
        fi  
      shell: bash