name: 'Grid.ai Login Test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittests:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        python-version: [3.8,3.9]       
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2     
      - uses: gridai-actions/gridai-login@main
        with:
          python-version: ${{ matrix.python-version }}
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}  
