name: 'Login Linux'
on:
  push:
    paths:
      - action.yml
      - .github/workflows/unittest.yml
      - .github/workflows/unittest-login.yml

jobs:
  unittests:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: gridai-actions/.github/workflows/unittest.yml@main
        with:
          os: ${{ matrix.os }}
