name: 'Login Win'
on:
  pull_request:
    paths:
      - action.yml
      - gridai.py
      - .github/workflows/unittest.yml
      - .github/workflows/unittest-linux.yml
jobs:
  login:
    uses: gridai-actions/gridai-login/.github/workflows/unittest.yml@v0
    with:
      os: windows-latest
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}      
