name: 'Login Linux'
on:
  push:
    paths:
      - action.yml
      - .github/workflows/unittest.yml
      - .github/workflows/unittest-linux.yml
jobs:
  login:
    uses: gridai-actions/gridai-login/.github/workflows/unittest.yml@main
    with:
      os: ubuntu-latest
    
