name: 'Grid.ai Login Test'
on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  unittests:
    strategy:
      matrix:
        os: [ubuntu-latest]         # os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.8]       # [3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2     
      - uses: gridai-actions/gridai-action-login@main
        with:
          username: ${{ secrets.GRIDAI_USERNAME }} 
          key: ${{ secrets.GRIDAI_KEY }}  
